name: Release Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release_linux:
    name: linux cppandaction release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release RTMIDI_BUILD_TESTING=OFF

      - name: Build
        run: cmake --build ./build --config Release

      - name: Create Artifact
        run: |
          mkdir release
          cp build/main release/main
      
      - name: Publish Linux Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cppandaction linux release
          path: release

  release_macos:
    name: macOS cppandaction release
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release RTMIDI_API_JACK=OFF RTMIDI_BUILD_TESTING=OFF

      - name: Build
        run: cmake --build ./build --config Release

      - name: Create Artifact
        run: |
          mkdir release
          cp build/main release/main
      
      - name: Publish MacOS Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cppandaction macOS release
          path: release

  # Artifac creation not working
  # release_windows:
  #   name: windows cppandaction release
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Create Build Directory
  #       run: cmake -E make_directory ${{github.workspace}}/build

  #     - name: Configure CMake
  #       run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

  #     - name: Build
  #       run: cmake --build ./build --config Release

  #     - name: Create Artifact
  #       run: |
  #         mkdir release
  #         copy build/main.exe release/main.exe
      
  #     - name: Publish Windows Artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: cppandaction windows release
  #         path: release
  # Artifac creation not working --      
